### ISSUE TITLE
The meadowrun AMI is not available in ca-central-1

### ISSUE THREAD

**Issue by agarzon** [meadowdata/meadowrun#265]
I was not expecting that to happen, I was following this tutorial : https://medium.com/@meadowrun/how-to-fine-tune-stable-diffusion-on-ec2-e305f077fb78

There are G4 and G5 instances available in ca-central-1, dont know why this is not supported.

Full error:
`ValueError: The meadowrun AMI is not available in ca-central-1. Please ask the meadowrun maintainers to add support for this region: https://github.com/meadowdata/meadowrun/issues and try a supported region for now: us-east-2, us-east-1, us-west-1, us-west-2, eu-central-1, eu-west-1, eu-west-2, eu-west-3, eu-north-1
`

**Comment by kurtschelfthout** [comment]
This is because meadowrun relies on some public AMI (disk images) being available, which are hosted on @hrichardlee's account. Hosting these costs some money (according to size of the image and number of regions it's hosted in), so we didn't host them in all possible regions.

Any of the listed regions should work.

If you don't want to change regions, and and up the difficulty level, you could create your own AMI and upload it to your own account. Currently you'd have to use meadowrun from source though (as the AMI ids per version are hardcoded). There are some scripts for that we use for development.

Going forward we should probably make that part of the install process...
